### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by niraj998** [saimoomedits/eww-widgets#1]
if you're using bashism mark it as bash script 

eww-widgets/eww/bar/scripts ➜  ./battery 
./battery: 12: [[: not found
./battery: 14: [[: not found
eww-widgets/eww/bar/scripts ➜  ./wifi 
./wifi: 19: [[: not found
./wifi: 21: [[: not found
./wifi: 23: [[: not found

Also if you're crediting someone.
you should also add why you're crediting them.
like "Credits to *person* for *something* "

**Comment by saimoomedits** [comment]
thanks
